import Footer from "@/components/footer-landing";
import GradientButton from "@/components/gradient-button";
import Head from "next/head";
import Image from "next/image";

function BackgroundVideo({ video }) {
  return (
    <>
      <video
        autoPlay
        loop
        muted
        className="hidden md:block absolute z-[-1] w-auto min-w-full min-h-full bottom-0 max-w-full  overflow-hidden"
      >
        <source src={video} type="video/mp4" />
        Your browser does not support the video tag.
      </video>
      <div className="hidden bg-[#030413] opacity-20 md:block absolute z-[-1] w-auto min-w-full min-h-full bottom-0 max-w-full  overflow-hidden"></div>
    </>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#030413] opacity-90">
        <div className="bg-[url('../../public/bg.svg')] bg-no-repeat bg-cover bg-center">
          <div className="px-4 lg:px-0 mx-auto max-w-[1080px] flex justify-center flex-col min-h-[100vh]">
            <div className="flex justify-center flex-row">
              <div className="flex flex-col justify-between text-center h-[100vh] py-10 md:py-32">
                <h1 className="text-4xl sm:text-5xl font-extrabold text-[#E4E4ED] ">
                  coinvise
                </h1>
                <div className="text-4xl tracking-tight font-extrabold text-[#E4E4ED] sm:text-5xl md:text-7xl lg:px-32 space-y-5">
                  <h2 className="block xl:inline">
                    Simplified Community Monetization & Growth
                  </h2>
                  <h3 className="block text-[#AEACC9] font-medium text-2xl lg:px-32">
                    Leading communities trust our no-code tools for airdrops and
                    NFT memberships
                  </h3>
                </div>
                <GradientButton link="/dashboard" title="Use coinvise" />
              </div>
            </div>
          </div>
        </div>
        <div className="px-4 lg:px-0 mx-auto max-w-[1080px] flex justify-center flex-col min-h-[100vh] bg-[url('../../public/arch.png')] bg-no-repeat bg-contain bg-center">
          <div className="flex justify-center flex-row">
            <div className="flex flex-col justify-center text-center h-[100vh] py-32 lg:px-32 space-y-20">
              <h2 className="text-4xl font-medium text-[#E4E4ED] sm:text-5xl md:text-7xl ">
                Give your Community Superpowers
              </h2>
              <h3 className="text-[#AEACC9] leading-relaxed font-medium text-2xl lg:px-32">
                Leading communities trust our no-code tools for airdrops and NFT
                memberships
              </h3>
            </div>
          </div>
        </div>
        <div className="pt-[110px] md:pt-4 px-4 lg:px-0 mx-auto max-w-[1080px] flex md:justify-center items-center flex-col md:flex-row min-h-[40vh]">
          <div className="w-full md:w-1/2 flex justify-center flex-col">
            <div className="flex flex-col justify-center md:h-[100vh] lg:px-32 overflow-hidden">
              <Image
                src="/coindeck.webp"
                width="300"
                height="100"
                alt="coindeck"
                className="absolute w-[150px] md:w-[300px] left-[50%] md:left-auto z-20"
              />
              <Image
                src="/coindeck.webp"
                width="300"
                height="100"
                alt="coindeck"
                className="absolute w-[150px] md:w-[300px] left-[50%] md:left-auto ml-[-80px] md:ml-[-120px] mt-[-50px] md:mt-[-150px] z-10"
              />
              <Image
                src="/coindeck.webp"
                width="300"
                height="100"
                alt="coindeck"
                className="absolute w-[150px] md:w-[300px] left-[50%] md:left-auto ml-[-160px] md:ml-[-240px] mt-[-100px] md:mt-[-300px]"
              />
            </div>
          </div>
          <div className="pt-[120px] md:pt-0 w-full md:w-1/2 flex justify-center text-center md:text-left flex-col">
            <div className="flex flex-col justify-center md:h-[100vh] space-y-5 md:space-y-10">
              <h2 className="text-3xl font-medium text-[#E4E4ED] sm:text-5xl block">
                <p>Industry leaders</p>
                <p>build with Coinvise</p>
              </h2>
              <p className="text-[#AEACC9] leading-relaxed font-medium text-1xl sm:text-2xl">
                Work with us to integrate our ecosystem of tooling into your
                infrastructure
              </p>
              <GradientButton link="/dashboard" title="Get in Touch" />
            </div>
          </div>
        </div>
        <div className="lg:px-0 mx-auto flex justify-center flex-col min-h-[60vh] space-y-4">
          <div className="flex justify-center text-[#E4E4ED] space-y-4 md:space-y-0 md:space-x-4 flex-col md:flex-row">
            <div className="bg-black w-full md:w-2/3 rounded-r-lg p-r-10 p-12 flex flex-col justify-center items-center text-center space-y-4">
              <div className="flex items-center space-x-3 max-w-[360px] w-full">
                <div className="w-full">
                  <p className="text-sm">POWERFUL</p>
                  <p className="text-4xl font-medium">Integrations</p>
                </div>
              </div>
              <div className="flex space-x-4">
                <div className="bg-[#39376C] w-[50px] h-[50px] flex items-center justify-center p-[10px] rounded-full">
                  <Image
                    src="/smart-contract.svg"
                    width="40"
                    height="40"
                    alt="icon"
                  />
                </div>
                <div className="bg-[#39376C] w-[50px] h-[50px] flex items-center justify-center p-[10px] rounded-full">
                  <Image
                    src="/smart-contract.svg"
                    width="40"
                    height="40"
                    alt="icon"
                  />
                </div>
                <div className="bg-[#39376C] w-[50px] h-[50px] flex items-center justify-center p-[10px] rounded-full">
                  <Image
                    src="/smart-contract.svg"
                    width="40"
                    height="40"
                    alt="icon"
                  />
                </div>
              </div>
            </div>
            <div className="bg-black w-full md:w-1/3 rounded-l-lg p-12 flex flex-col items-center md:items-start justify-center text-center lg:text-left">
              <div className="flex flex-col space-y-3 lg:space-y-0 lg:flex-row items-center space-x-5 md:space-x-2 lg:space-x-5 max-w-[720px]">
                <div className="bg-[#39376C] w-[50px] h-[50px] flex items-center justify-center p-[10px] rounded-full">
                  <Image
                    src="/smart-contract.svg"
                    width="40"
                    height="40"
                    alt="icon"
                  />
                </div>
                <div>
                  <p className="text-sm">BATTLE TESTED</p>
                  <p className="text-4xl font-medium">Smart Contracts</p>
                </div>
              </div>
            </div>
          </div>
          <div className="flex justify-center text-[#E4E4ED] space-y-4 md:space-y-0 md:space-x-4 flex-col md:flex-row">
            <div className="bg-black w-full md:w-1/3 rounded-r-lg p-r-10 p-12 flex flex-col justify-center items-center text-center space-y-4">
              <div className="flex items-center space-x-3 max-w-[360px] w-full">
                <div className="w-full">
                  <p className="text-sm">COMPATIBLE</p>
                  <p className="text-4xl font-medium">Networks</p>
                </div>
              </div>
              <div className="flex space-x-2">
                <div className="bg-[#39376C] w-[50px] h-[50px] flex items-center justify-center p-[10px] rounded-full">
                  <Image
                    src="/smart-contract.svg"
                    width="40"
                    height="40"
                    alt="icon"
                  />
                </div>
                <div className="bg-[#39376C] w-[50px] h-[50px] flex items-center justify-center p-[10px] rounded-full">
                  <Image
                    src="/smart-contract.svg"
                    width="40"
                    height="40"
                    alt="icon"
                  />
                </div>
                <div className="bg-[#39376C] w-[50px] h-[50px] flex items-center justify-center p-[10px] rounded-full">
                  <Image
                    src="/smart-contract.svg"
                    width="40"
                    height="40"
                    alt="icon"
                  />
                </div>
              </div>
            </div>
            <div className="bg-black w-full md:w-2/3 rounded-l-lg p-l-10 p-12 flex flex-col items-start justify-center">
              <div className="flex items-center space-x-5 max-w-[720px]">
                <div>
                  <p className="text-sm">COMPATIBLE WITH YOUR</p>
                  <p className="text-4xl font-medium">Trusted Wallets</p>
                </div>
                <div className="flex space-x-4">
                  <div className="bg-[#39376C] w-[50px] h-[50px] flex items-center justify-center p-[10px] rounded-full">
                    <Image
                      src="/smart-contract.svg"
                      width="40"
                      height="40"
                      alt="icon"
                    />
                  </div>
                  <div className="bg-[#39376C] w-[50px] h-[50px] flex items-center justify-center p-[10px] rounded-full">
                    <Image
                      src="/smart-contract.svg"
                      width="40"
                      height="40"
                      alt="icon"
                    />
                  </div>
                  <div className="bg-[#39376C] w-[50px] h-[50px] flex items-center justify-center p-[10px] rounded-full">
                    <Image
                      src="/smart-contract.svg"
                      width="40"
                      height="40"
                      alt="icon"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-[url('../../public/arch.png')] bg-no-repeat bg-cover bg-center bg-fixed">
          <div className="px-4 lg:px-0 mx-auto max-w-[1080px] flex justify-center flex-col min-h-[70vh]">
            <div className="flex justify-center flex-row">
              <div className="flex flex-col justify-center text-center h-[70vh] py-32 lg:px-32 space-y-20">
                <h2 className="text-4xl font-medium text-[#E4E4ED] sm:text-5xl">
                  Start Growing Your <br /> Community Today
                </h2>
                <GradientButton link="/dashboard" title="Alright, I,m in" />
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
